on: [push, pull_request]

jobs:
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
            components: clippy
      - run: cargo clippy --no-deps -- -Dwarnings
      - run: cargo clippy --no-deps --no-default-features -- -Dwarnings

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
            components: rust-docs
      - run: cargo doc --no-deps
      - run: cargo doc --no-deps --no-default-features

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
            components: rustfmt
      - run: cargo fmt --check
  build_linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-afl
      - run: cargo build --release --workspace --exclude serial-fuzz-target
      - run: cargo build --release --no-default-features --workspace --exclude serial-fuzz-target
      - run: cargo afl build --package serial-fuzz-target
      - run: cargo build --example linux_usb --no-default-features --features "alloc std"
      - run: cargo build --example mac_usb
      - run: cargo build --example mac_usb_hr_display
      - run: cargo build --example mac_usb_tx
      - run: cargo build --example no_std_ant --no-default-features
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --tests
